on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'What environment do you want to deploy to?'
        default: 'dev'
        required: false
        type: choice
        options:
        - dev
        - test
        - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURETEAM4 }}
    - uses: azure/arm-deploy@v2
      with:
        resourceGroupName: ${{ vars.RESOURCEGROUP }}
        template: InfrastructureAsCode/main.bicep
        parameters: environment=${{ inputs.environment }}